server:
  port: ${PORT:0}

gateway:
  ip: 192.168.29.144

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
spring:
  application:
    name: users-ws
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver  
    
  devtools:
    restart:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      albums-ws:
        failure-rate-threshold: 50  #The Threshold Percentage Above Which the Circuit Breaker will move from Closed to Open State.
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 1000  #Time in milliseconds, in which the circuit breaker is to stay in open state before moving to half-open state
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        
  retry:
    instances:
      albums-ws:
        max-attempts: 3
        wait-duration: 2
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 5
        event-consumer-buffer-size: 10
        
        
